### ISSUE TITLE
MXL7 Revision

### ISSUE THREAD

**Issue by CalebBartle** [sanderkl/PSMeraki#11]
Hi Sanderkl,

I have really used a lot of your PSMeraki module in a lot of project I work on. I wanted to contribute some fixes to the Update-MXL7FWRule script. The improvements i made also allow whitelisted and blacklisted country rules to be added via the API  as that wasn't originally added. Let me know your thoughts.

function Update-MrkNetworkMXL7FwRule{
    [CmdletBinding()]
    Param (
        [Parameter(Mandatory)][ValidateNotNullOrEmpty()][String]$networkId,
        [ValidateSet("deny")][String]$policy="deny",
        [Parameter(Mandatory)][ValidateNotNullOrEmpty()][ValidateSet("application", "applicationCategory","host","port","ipRange", "whitelistedCountries", "blacklistedCountries")][String]$type,
        [Parameter(Mandatory)][ValidateNotNullOrEmpty()]$value,
        [Parameter(Mandatory)][ValidateNotNullOrEmpty()][ValidateSet("add", "remove")][String]$action,
        [Parameter()][switch]$reset
    )
    
    $ruleset = @()
    if (-not $reset){
        $ruleset = (Get-MrkNetworkMXL7FwRule -networkId $networkId).rules
    }
    #the value in the rule-object is an object itself that cannot be compared as string
    if ($type -match "application"){
        $PSoValue = [pscustomobject]$value
    } else {
        $PSoValue = $value
    }
    
    #populate the to-be ruleset first with the existing rules (will be empty in case of reset)
    $applyRules = @()
    ForEach ($rule in $ruleset){
    
        #if the action is delete and the rule specifications policy/type/value are equal do not add it back to the ruleset. 
        if ($action -eq 'remove' -and `
            ($rule.policy -eq $policy -and `
            $rule.type -eq $type -and `
            [string]$PSoValue -match $rule.value)){
                "No longer adding this rule: $value";
                continue
            }
    
        if ($action -eq 'add' -and `
            ($rule.policy -eq $policy -and `
                $rule.type -eq $type -and `
                $rule.value -match $PSoValue)){
                    "Not adding new rule as it is already present: $value";
                    $rulePresent = $true
                }
              
        #add this exising rule into the $ruleset object
        $ruleEntry = [PSCustomObject]@{
            policy = $rule.policy
            type   = $rule.type
            value  = $rule.value
        }
    
        $applyRules += $ruleEntry
    
    }
    
    #append the new ruleobject to the applyRules
    if ($action -eq 'add' -and $true -ne $rulePresent){
        $ruleEntry = New-Object -TypeName PSObject -Property @{
            policy = $policy
            type   = $type
            value  = $PSoValue
        }
    
        $applyRules += $ruleEntry
    };
    
    #construct the full ruleObject to push into the $body of the RESTapi request
    $ruleObject = New-Object -TypeName PSObject -Property @{
        rules = $applyRules
    }
    
    if($true -ne $rulePresent){
    
        $request = Invoke-MrkRestMethod -Method PUT -ResourceID ('/networks/' + $networkId + '/l7FirewallRules') -body $ruleObject
        return $request
    
        # construct the uri of the MR device in the current organization
        # $uri = "$(Get-MrkOrgEndpoint)/networks/$networkId/l7FirewallRules"    
        # try {
        #     $request = Invoke-RestMethod -Method Put `
        #     -ContentType 'application/json' `
        #     -Headers (Get-MrkRestApiHeader) `
        #     -Uri $uri `
        #     -Body ($ruleObject | ConvertTo-Json -Depth 4) -Verbose -ErrorAction Stop
    
        #     Write-Host "succesfully updated firewall rules" -ForegroundColor Green
        # }
        # catch
        # {
        #     $_.exception
        # }
    
        # Return ($request | ConvertTo-Json)
    
    }
}

**Comment by sanderkl** [comment]
I added those options, removed all the commented code. 

Cheers!
