### ISSUE TITLE
Set-MrkRestApi always asking for key despite being passed it

### ISSUE THREAD

**Issue by airitcs** [sanderkl/PSMeraki#14]
Hi,

I am finding that when I put the following into Powershell, I'm being asked for the REST API code.

`
PS C:\Scripts> Set-MrkRestApiKey d8b5********************c25327e720946c57           (redacted, of course!)

Enter Meraki REST API key:
`

I've tried specifying the -key parameter name but get the same.

Any idea what's going on?  Is this a bug?

Cheers
Tim.

**Comment by sanderkl** [comment]
I fixed this issue in the upcoming v2 of the module. 
a similar issue is fixed too in v2, v1.1.3 threw an error once after asking for the rest api key.
