### ISSUE TITLE
Updates to PSMeraki

### ISSUE THREAD

**Issue by CalebBartle** [sanderkl/PSMeraki#17]
Sander,

I wanted to know if you would be interested in looking at my branch of PSMeraki. It is a heavy change that I have not posted to git yet and I see you have made some updates to the module. Please reach out to me directly, I want to schedule some time where I can introduce you to an automation toolkit  I am building alongside this module.

Let me know your thoughts.

Contact: calebbartle@gmail.com

**Comment by sanderkl** [comment]
done!
