### ISSUE TITLE
Incorrect list of exported functions?

### ISSUE THREAD

**Issue by jrbarrick** [sanderkl/PSMeraki#18]
Looks like these functions are missing from the ExportedFunctions:
Get-MrkRestApiVersion
Restart-MrkDevice
Set-MrkNetworkSiteToSiteVPN
Set-MrkRestApiVersion

This function is also listed, but I think it's been removed?
Test-MrkRestApiKey

**Comment by sanderkl** [comment]
yes, while updating .psd1 file using Update-ModuleManifest I didn't include both CmdletsToExport FunctionsToExport parameters. That has been fixed in 2.0.1.

Thanks for the feedback!
