### ISSUE TITLE
Set-MrkDevice

### ISSUE THREAD

**Issue by cwatsonjr** [sanderkl/PSMeraki#24]
I am having difficulties running the above reference command. Below is the error message received. We are currently not using any tags in the Meraki environment. I've included and excluded the tag parameter with similar results. Any help would be very much appreciated. 

Ex: 
HTTP Error: The remote server returned an error: (400) Bad Request..Exception.Message
REST Error: 'tags' must be an array

**Comment by sanderkl** [comment]
If you can share the relevant lines of code that produces the error, I might be able to see what goes wrong.

**Comment by sanderkl** [comment]
no response.
I dont think its an issue in the module.
